version: '3'

services:
    mongo:
        image: mongo
        container_name: mongodb
    web:
        depends_on:
            - mongo
        build: ./web/
        volumes:
            - ./web/resources:/usr/src/app/resources
            - ./web/templates:/usr/src/app/templates
            - ./web/secret-data:/usr/src/app/secret-data
        ports:
        - "8000:8000"
    mongo-express:
        image: mongo-express
        ports:
        - "8081:8081"